"""
Data Schemas for the Genesis Pipeline Output.
Defines the structure of the Story DNA, Scene Beats, and Visual/Audio Manifests.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

# --- Narrative Layers ---

class NarrativeDNA(BaseModel):
    """The core creative identity of the production."""
    territory: str = Field(description="The genre/emotional space (e.g., 'Melancholic Drama')")
    archetype: str = Field(description="The central character arc type (e.g., 'The Silent Withdrawal')")
    theme: str = Field(description="The philosophical core or moral of the story")
    visual_motif: str = Field(description="A recurring visual element (e.g., 'Clocks', 'Cold Light')")

# --- Scene & Script Layers ---

class DialogueLine(BaseModel):
    """A single spoken line within a scene."""
    speaker: str
    delivery: str = Field(description="Tone of voice (e.g., 'Softly', 'Shouting', 'Whispering')")
    text: str
    subtext: str = Field(default="", description="What is implied but not said")

class SceneBeat(BaseModel):
    """A single scene within the screenplay."""
    id: int
    title: str = Field(description="Short, punchy scene title")
    location: str = Field(description="Setting (e.g., 'Bathroom', 'Kitchen')")
    time: str = Field(description="Time of day/period")
    duration_estimate: str = Field(default="2 Mins") # Estimated runtime for this scene
    
    visual_direction: str = Field(description="Cinematic instructions (Camera moves, lighting)")
    
    dialogue: List[DialogueLine] = Field(default_factory=list)
    
    voice_over: Optional[str] = Field(default=None, description="Internal monologue / Narration text")
    
    audio_cues: List[str] = Field(default_factory=list) # e.g., ["Clock ticking", "Distant train"]

class ScreenplayOutput(BaseModel):
    """The complete script generated by the Storyteller Agent."""
    title: str
    logline: str
    scenes: List[SceneBeat]

# --- Production Layers ---

class AudioManifest(BaseModel):
    """Global and scene-specific audio requirements."""
    global_mood: str = Field(description="Dominant musical tone")
    soundtrack_zones: Dict[str, str] = Field(default_factory=dict) # Act -> Mood
    prosody_override: Dict[int, str] = Field(default_factory=dict) # Scene ID -> Voice Tone

class VisualBundle(BaseModel):
    """Generated prompts for the Image Generation Agent."""
    negative_prompts: List[str]
    prompts: List[str] # Corresponds 1-to-1 with scenes

# --- Full Genesis Output ---

class GenesisOutput(BaseModel):
    """The unified output of the entire Genesis Pipeline."""
    dna: NarrativeDNA
    screenplay: ScreenplayOutput
    audio_manifest: AudioManifest
    visual_prompts: VisualBundle
    audit_status: str = "PASSED"
