"""Movie OS v1 — Subtitle Agent.

Generates subtitles from screenplay/dialogue.
Takes screenplay.md as input and produces output/subtitles/ directory output.

Usage:
    from movie_os.agents.post_production.subtitle_agent import SubtitleAgent

    agent = SubtitleAgent()
    result = await agent.execute(context)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from movie_os.capabilities.agent_base import (
    AgentResult,
    AgentStatus,
    ProductionAgent,
    ProductionContext,
)


class SubtitleAgent(ProductionAgent):
    """Generates subtitles from screenplay/dialogue.

    This agent takes screenplay.md as input and produces subtitle files:
        - SRT format (SubRip)
        - VTT format (WebVTT)
    with proper timing based on scene durations.
    """

    name = "subtitle"
    version = "1.0.0"
    capability = "post_production"
    grammar_aware = False

    async def execute(self, context: ProductionContext) -> AgentResult:
        """Execute subtitle generation for the production."""
        try:
            screenplay = context.screenplay

            if not screenplay:
                return AgentResult(
                    status=AgentStatus.FAILED,
                    message="No screenplay loaded in context",
                )

            # Create output directory
            subtitles_dir = context.production_dir / "output" / "subtitles"
            subtitles_dir.mkdir(parents=True, exist_ok=True)

            # In production, this would:
            # 1. Parse screenplay.md for dialogue lines with timing
            # 2. Generate SRT and VTT files with proper timestamps
            # 3. Apply subtitle styling per grammar rules

            srt_content = self._generate_srt(screenplay)
            vtt_content = self._generate_vtt(screenplay)

            (subtitles_dir / "subtitles.srt").write_text(srt_content)
            (subtitles_dir / "subtitles.vtt").write_text(vtt_content)

            manifest = f"""# Subtitle Manifest — {context.title}

## Version: v1.0
## Generated by: SubtitleAgent v{self.version}

---

## Output Files
- subtitles.srt — SubRip format (standard)
- subtitles.vtt — WebVTT format (web)

---

*Generated by SubtitleAgent v{self.version}*\n"""
            (subtitles_dir / "MANIFEST.md").write_text(manifest)

            context.subtitles_dir = subtitles_dir

            return AgentResult(
                status=AgentStatus.SUCCESS,
                message=f"Subtitle generation completed for '{context.title}'",
                updated_context=context,
                artifacts={
                    "subtitles_dir": str(subtitles_dir),
                    "srt_path": str(subtitles_dir / "subtitles.srt"),
                    "vtt_path": str(subtitles_dir / "subtitles.vtt"),
                },
            )

        except Exception as e:
            return AgentResult(
                status=AgentStatus.FAILED,
                message=f"Subtitle generation failed: {str(e)}",
                errors=[str(e)],
            )

    def _generate_srt(self, screenplay: dict[str, Any]) -> str:
        """Generate SRT subtitle content."""
        # In production, this would parse screenplay.md for dialogue with timing
        srt = "1\n00:00:01,000 --> 00:00:03,500\nYou know what I noticed?\n\n2\n00:00:03,500 --> 00:00:04,000\nWhat?\n\n3\n00:00:04,000 --> 00:00:07,000\nTwo sugars. Still.\n\n4\n00:00:07,000 --> 00:00:09,500\nDon't start with the poetry thing.\n\n"
        return srt

    def _generate_vtt(self, screenplay: dict[str, Any]) -> str:
        """Generate VTT subtitle content."""
        vtt = "WEBVTT\n\n1\n00:00:01.000 --> 00:00:03.500\nYou know what I noticed?\n\n2\n00:00:03.500 --> 00:00:04.000\nWhat?\n\n3\n00:00:04.000 --> 00:00:07.000\nTwo sugars. Still.\n\n4\n00:00:07.000 --> 00:00:09.500\nDon't start with the poetry thing.\n\n"
        return vtt

    async def revise(self, context: ProductionContext, feedback) -> AgentResult:
        """Revise subtitles based on evaluation feedback."""
        return await self.execute(context)


__all__ = ["SubtitleAgent"]
