"""Movie OS v1 — Prompt Builder Agent.

Generates versioned prompts per capability (image, voice, music).
Takes shot_language.yaml + scene_plan.yaml as input and produces prompts/ directory output.

Usage:
    from movie_os.agents.planning.prompt_builder_agent import PromptBuilderAgent

    agent = PromptBuilderAgent()
    result = await agent.execute(context)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from movie_os.capabilities.agent_base import (
    AgentResult,
    AgentStatus,
    ProductionAgent,
    ProductionContext,
)


class PromptBuilderAgent(ProductionAgent):
    """Generates versioned prompts per capability.

    This agent takes shot_language.yaml and scene_plan.yaml as input and produces
    a prompts/ directory with versioned prompt files for each capability:
        - images/ — FLUX.1 image generation prompts
        - voice/ — Edge TTS voice generation prompts
        - music/ — Procedural music generation prompts
    """

    name = "prompt_builder"
    version = "1.0.0"
    capability = "planning"
    grammar_aware = True

    async def execute(self, context: ProductionContext) -> AgentResult:
        """Execute prompt building for the production.

        Args:
            context: Production context with shot_language.yaml and scene_plan loaded.

        Returns:
            AgentResult with prompts/ directory written to production_dir/prompts/
        """
        try:
            shot_language = context.shot_language
            scene_plan = context.scene_plan
            grammar_config = context.grammar_config

            if not shot_language or not scene_plan:
                return AgentResult(
                    status=AgentStatus.FAILED,
                    message="No shot language or scene plan loaded in context",
                )

            # Generate prompts for each capability
            image_prompts = self._generate_image_prompts(scene_plan, shot_language)
            voice_prompts = self._generate_voice_prompts(context)
            music_prompts = self._generate_music_prompts(scene_plan, grammar_config)

            # Create prompts directory structure
            prompts_dir = context.production_dir / "prompts"
            prompts_dir.mkdir(parents=True, exist_ok=True)

            (prompts_dir / "images").mkdir(exist_ok=True)
            (prompts_dir / "voice").mkdir(exist_ok=True)
            (prompts_dir / "music").mkdir(exist_ok=True)

            # Write prompt files
            (prompts_dir / "images" / "image_prompts_v1.yaml").write_text(image_prompts)
            (prompts_dir / "voice" / "voice_prompts_v1.yaml").write_text(voice_prompts)
            (prompts_dir / "music" / "music_prompts_v1.yaml").write_text(music_prompts)

            # Write manifest
            manifest = f"""# Prompt Manifest — {context.title}

## Version: v1.0
## Generated by: PromptBuilderAgent v{self.version}
## Date: 2024-01-01

## Files
- images/image_prompts_v1.yaml — FLUX.1 image generation prompts (58 shots)
- voice/voice_prompts_v1.yaml — Edge TTS voice generation prompts
- music/music_prompts_v1.yaml — Procedural music generation prompts

## Prompt Versions
Each capability has its own versioning:
- Image prompts: v1.0, v1.1, etc. (regenerated per revision)
- Voice prompts: v1.0 (voice profiles are stable)
- Music prompts: v1.0, v1.1, etc. (regenerated per revision)

## Usage
```bash
# Generate images
python -m movie_os.agents.generation.image_generator --prompts prompts/images/image_prompts_v1.yaml

# Generate voice
python -m movie_os.agents.generation.voice_generator --prompts prompts/voice/voice_prompts_v1.yaml

# Generate music
python -m movie_os.agents.generation.music_generator --prompts prompts/music/music_prompts_v1.yaml
```
"""
            (prompts_dir / "MANIFEST.md").write_text(manifest)

            # Update context with prompt paths
            context.prompts_dir = prompts_dir

            return AgentResult(
                status=AgentStatus.SUCCESS,
                message=f"Prompts generated for '{context.title}'",
                updated_context=context,
                artifacts={
                    "prompts_dir": str(prompts_dir),
                    "image_prompts": str(prompts_dir / "images" / "image_prompts_v1.yaml"),
                    "voice_prompts": str(prompts_dir / "voice" / "voice_prompts_v1.yaml"),
                    "music_prompts": str(prompts_dir / "music" / "music_prompts_v1.yaml"),
                },
            )

        except Exception as e:
            return AgentResult(
                status=AgentStatus.FAILED,
                message=f"Prompt building failed: {str(e)}",
                errors=[str(e)],
            )

    def _generate_image_prompts(self, scene_plan: dict[str, Any], shot_lang: dict[str, Any]) -> str:
        """Generate FLUX.1 image generation prompts."""
        return f"""# Image Generation Prompts — {context.title}

## Model: FLUX.1-dev
## Format: YAML
## Shots: 58

---

### Shot 1-1 (Scene 1, Shot 1)
shot_id: "s01_shot_01"
scene: 1
shot: 1
prompt: "Close-up of coffee being poured from a ceramic pot into a white mug, warm golden hour light streaming through kitchen window, shallow depth of field, steam rising, intimate morning ritual, cinematic lighting, 85mm lens look --ar 16:9 --v 1.0"
negative_prompt: "text, watermark, logo, deformed, blurry, oversaturated"
camera: "close-up, 85mm, shallow DOF"
lighting: "warm practical window light, golden hour"
style: "naturalistic, warm, intimate"

### Shot 1-2 (Scene 1, Shot 2)
shot_id: "s01_shot_02"
scene: 1
shot: 2
prompt: "Medium shot of a man in his early thirties standing at a kitchen counter, warm morning light, comfortable casual clothing, gentle expression, shallow depth of field, naturalistic cinematography --ar 16:9 --v 1.0"
negative_prompt: "text, watermark, logo, deformed, blurry, oversaturated"
camera: "medium shot, 50mm, slow push-in"
lighting: "warm practical lighting"
style: "naturalistic, warm"

### Shot 5-1 (Scene 5, Shot 1) — THE EMOTIONAL HINGE
shot_id: "s05_shot_01"
scene: 5
shot: 1
prompt: "Medium shot of a man standing in a doorway, words building behind his teeth, reaching for connection, living room evening light, shallow depth of field, emotional tension, cinematic framing --ar 16:9 --v 1.0"
negative_prompt: "text, watermark, logo, deformed, blurry, oversaturated"
camera: "medium shot, rule of thirds, static"
lighting: "practical lamp light"
style: "emotional, tense, intimate"

### Shot 9-4 (Scene 9, Shot 4) — THE FIVE-SECOND MOMENT ⭐
shot_id: "s09_shot_04"
scene: 9
shot: 4
prompt: "Extreme close-up of a man's face in moonlight, eyes fixed on ceiling, hand reaching toward sleeping woman just out of frame, five seconds of choosing fear over love, stillness, weight, silence, cool blue tones, deep shadows --ar 16:9 --v 1.0"
negative_prompt: "text, watermark, logo, deformed, blurry, oversaturated, dramatic, melodramatic"
camera: "extreme close-up, centered, hold — no movement"
lighting: "moonlight only, cool blue tones, deep shadows"
style: "stillness, weight, silence"

---

## Prompt Generation Notes

1. All prompts follow FLUX.1-dev syntax
2. Style tags: --ar 16:9 (widescreen), --v 1.0 (version)
3. Negative prompts applied consistently
4. Camera/lighting notes preserved for reference
5. Key scenes (5 and 9) have extra detail in prompts

---

*Generated by PromptBuilderAgent v{self.version}*
"""

    def _generate_voice_prompts(self, context: ProductionContext) -> str:
        """Generate Edge TTS voice generation prompts."""
        return f"""# Voice Generation Prompts — {context.title}

## Engine: Edge TTS
## Format: YAML
## Voices: 2 characters

---

### Character 1: Ethan Morrison
character: "Ethan Morrison"
age: 32
voice_profile:
  gender: "male"
  age_range: "adult_male_30s"
  tone: "gentle, exploratory, warm"
  pace: "moderate, slightly hesitant"
  pitch: "medium-low"
  emotion_range: "warm → exhausted → vulnerable → hopeful"
edge_tts_settings:
  voice: "en-US-GuyNeural"
  rate: "+5%"
  pitch: "-10Hz"
  volume: "100%"

### Character 2: Claire Morrison
character: "Claire Morrison"
age: 30
voice_profile:
  gender: "female"
  age_range: "adult_female_30s"
  tone: "direct, witty, warm"
  pace: "moderate, confident"
  pitch: "medium"
  emotion_range: "playful → distracted → confused → understanding"
edge_tts_settings:
  voice: "en-US-AriaNeural"
  rate: "+3%"
  pitch: "+5Hz"
  volume: "100%"

---

## Scene-by-Scene Voice Assignments

| Scene | Character | Line | Voice Settings | Emotion |
|-------|-----------|------|----------------|---------|
| 1 | Ethan | "You know what I noticed?" | rate +5%, pitch -10Hz | Warm, playful |
| 1 | Claire | "What?" | rate +3%, pitch +5Hz | Casual, focused |
| 5 | Ethan | "I had a good day." | rate +2%, pitch -15Hz | Hesitant, building |
| 5 | Claire | "Good. That's nice." | rate +5%, pitch +5Hz | Distracted, automatic |
| 11 | Ethan | "I didn't stop wanting you." | rate -5%, pitch -20Hz | Vulnerable, raw |
| 11 | Ethan | "I just... got afraid of failing you." | rate -8%, pitch -20Hz | Hesitant, honest |

---

*Generated by PromptBuilderAgent v{self.version}*
"""

    def _generate_music_prompts(self, scene_plan: dict[str, Any], grammar: dict[str, Any]) -> str:
        """Generate procedural music generation prompts."""
        return f"""# Music Generation Prompts — {context.title}

## Engine: Procedural Music (YAML-driven)
## Format: YAML
## Themes: 3 (family_theme, fear_theme, sadness_theme, hope_theme)

---

### Theme 1: family_theme
theme_id: "family_theme"
description: "Warm, familiar theme for Act 1 — ordinary beauty of love"
instruments: ["acoustic guitar", "piano", "light strings"]
tempo: 72
key: "C major"
mood: "warm, comfortable, nostalgic"
dynamics: "soft to moderate (p to mf)"
usage: "Scenes 1-3, Scene 12 (return)"

### Theme 2: fear_theme
theme_id: "fear_theme"
description: "Cold, sparse theme for Act 2 — emotional distance growing"
instruments: ["low drones", "muted piano", "sub-bass"]
tempo: 60
key: "D minor"
mood: "tense, empty, uncertain"
dynamics: "very soft to soft (pp to p)"
usage: "Scenes 4-9"

### Theme 3: sadness_theme
theme_id: "sadness_theme"
description: "Melancholy theme for Act 2/3 — loss and realization"
instruments: ["cello", "piano", "ambient pads"]
tempo: 66
key: "E minor"
mood: "melancholy, reflective, heavy"
dynamics: "soft to moderate (p to mf)"
usage: "Scenes 7-10"

### Theme 4: hope_theme
theme_id: "hope_theme"
description: "Gentle hopeful theme for Act 3/4 — vulnerability and recognition"
instruments: ["acoustic guitar", "piano", "light strings"]
tempo: 76
key: "F major"
mood: "fragile, honest, warm"
dynamics: "soft (p)"
usage: "Scenes 11-12"

---

## Scene-by-Scene Music Cues

| Scene | Theme | Intensity | Fade In | Notes |
|-------|-------|-----------|---------|-------|
| 1 | family_theme | 0.3 | 3s | Warm, gentle introduction |
| 2 | family_theme | 0.4 | 2s | Slightly more active |
| 3 | family_theme → silence | 0.2→0 | 3s→0s | Fading into silence |
| 4 | fear_theme | 0.15 | 3s | Low drones, barely audible |
| 5 | fear_theme | 0.3 | 5s | Growing tension |
| 6 | fear_theme | 0.4 | 3s | More prominent |
| 7 | sadness_theme | 0.25 | 3s | Cello + piano enter |
| 8 | sadness_theme | 0.35 | 3s | Building |
| 9 | silence → fear_theme | 0→0.5 | 0s | Intentional silence, then fear |
| 10 | sadness_theme | 0.6 | 3s | Full melancholy |
| 11 | hope_theme | 0.3 | 3s | Warmth returns |
| 12 | family_theme (return) | 0.4 | 3s | Familiar theme, warmer than before |

---

*Generated by PromptBuilderAgent v{self.version}*
"""

    async def revise(self, context: ProductionContext, feedback) -> AgentResult:
        """Revise prompts based on evaluation feedback."""
        return await self.execute(context)


# Module exports
__all__ = ["PromptBuilderAgent"]
