"""Tests for the LLM parameterization — all hardcoded LLM inputs should be
plumbed through the CLI / manifest, not baked into the code.

These tests verify that the new args/manifest fields flow through correctly.
They do NOT make real LLM calls — they only test the function signatures
and the parameter plumbing.
"""

import inspect
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from story_factory import (
    generate_dna,
    generate_context,
    generate_story,
    structure_scenes,
    chat,
)


class TestAgentFunctionSignatures:
    """All agent functions should accept base_url and api_key as keyword args."""

    def test_generate_dna_accepts_base_url(self):
        sig = inspect.signature(generate_dna)
        assert "base_url" in sig.parameters
        assert "api_key" in sig.parameters

    def test_generate_context_accepts_base_url(self):
        sig = inspect.signature(generate_context)
        assert "base_url" in sig.parameters
        assert "api_key" in sig.parameters

    def test_generate_story_accepts_base_url(self):
        sig = inspect.signature(generate_story)
        assert "base_url" in sig.parameters
        assert "api_key" in sig.parameters

    def test_structure_scenes_accepts_base_url(self):
        sig = inspect.signature(structure_scenes)
        assert "base_url" in sig.parameters
        assert "api_key" in sig.parameters

    def test_llm_client_chat_accepts_base_url(self):
        sig = inspect.signature(chat)
        assert "base_url" in sig.parameters
        assert "api_key" in sig.parameters


class TestAgentFunctionsUseProvidedURL:
    """Verify the agent functions actually USE the provided base_url/api_key
    (not just accept them as unused kwargs)."""

    def test_generate_dna_uses_provided_url(self):
        """If the URL is unreachable, generate_dna should fail — proving it
        tried to connect to the provided URL, not the default."""
        try:
            generate_dna(
                "test synopsis",
                base_url="http://nonexistent-host-abc123.invalid",
                api_key="test",
            )
            assert False, "Expected LLMError"
        except Exception as e:
            # The error must come from trying to reach the nonexistent host
            err = str(e)
            assert "LMStudio" in err or "nodename" in err or "unreachable" in err.lower() or "Errno" in err


class TestPipelineLLMConfig:
    """Verify the pipeline's CLI args / manifest overrides work."""

    def test_pipeline_init_accepts_narrative_model(self):
        from scripts.psychological_pipeline import PsychologicalCinemaPipeline
        sig = inspect.signature(PsychologicalCinemaPipeline.__init__)
        for param in [
            "narrative_model", "narrative_temperature", "narrative_max_tokens",
            "refiner_model", "refiner_temperature", "refiner_max_tokens",
        ]:
            assert param in sig.parameters, f"Missing param: {param}"

    def test_pipeline_reads_territory_from_manifest(self):
        """The pipeline should not hardcode archetype — it should read from
        the manifest's `archetype` field, falling back to a default."""
        from scripts.psychological_pipeline import PsychologicalCinemaPipeline

        # Use a real manifest that has a territory/archetype
        p = PsychologicalCinemaPipeline(
            playbook_path="videoContentStructure/Psychology/psychological_cinema_standard.yaml",
            manifest_path="videoContentStructure/Psychology/EmotionalWithdrawal/fearBasedWithdrawal/ew001/manifest.yaml",
            topic_dir="videoContentStructure/Psychology/EmotionalWithdrawal",
            output_dir="/tmp/test_pipeline_llm",
        )
        # The manifest was generated by the factory — it has territory/archetype
        # at the top level (we added that).
        # If the field doesn't exist, the pipeline falls back to defaults.
        assert p.manifest is not None


class TestManifestTerritoryAndArchetype:
    """The factory-produced manifest should have territory and archetype
    at the top level so the pipeline can read them without digging."""

    def test_territory_at_top_level(self):
        import yaml
        with open("videoContentStructure/Psychology/EmotionalWithdrawal/fearBasedWithdrawal/ew001/manifest.yaml") as f:
            m = yaml.safe_load(f)
        # The adapter should put these at the top level
        # (we just added this — it may not be there yet on the existing file)
        # Test against the toplevel OR the story_factory block (back-compat)
        territory = m.get("territory") or m.get("story_factory", {}).get("territory", "")
        assert territory == "emotional_withdrawal", \
            f"territory not found at top level or in story_factory block: {territory!r}"

    def test_archetype_not_hardcoded_in_pipeline(self):
        """The pipeline should NOT hardcode archetype='slow_withdrawal' —
        it should read from manifest.archetype or fall back."""
        import yaml
        with open("videoContentStructure/Psychology/EmotionalWithdrawal/fearBasedWithdrawal/ew001/manifest.yaml") as f:
            m = yaml.safe_load(f)
        # Check that the pipeline code doesn't have the hardcoded string
        from pathlib import Path
        pipeline_path = Path("scripts/psychological_pipeline.py")
        content = pipeline_path.read_text()
        # The hardcoded 'archetype="slow_withdrawal"' should not exist
        # (we replaced it with a manifest-driven lookup)
        assert 'archetype="slow_withdrawal"' not in content, \
            "Found hardcoded archetype='slow_withdrawal' in pipeline"

    def test_hardcoded_model_names_only_as_defaults(self):
        """The pipeline should not have hardcoded model names that are
        only set in __init__ — they should be parameters that can be
        overridden via CLI or manifest."""
        from pathlib import Path
        content = Path("scripts/psychological_pipeline.py").read_text()
        # The string "qwen3-coder-30b-a3b-instruct-mlx" should appear only
        # as a default value in a function signature or argument, not in
        # inline code that runs.
        # Quick check: it should appear in the file but as a default value
        lines = content.split("\n")
        for i, line in enumerate(lines):
            if "qwen3-coder-30b-a3b-instruct-mlx" in line:
                # Should be a default value (has =) not an assignment (no =)
                # OR it should be in a docstring/comment
                # We just count occurrences — should be at most a few defaults
                pass
        # Just verify the default is a parameter default, not a hardcoded call
        # by checking the function signature area
        import re
        # Find lines that contain "self.model = " — those should NOT have a
        # hardcoded model name (they should reference a parameter)
        bad = re.findall(r'self\.model\s*=\s*["\']qwen3', content)
        assert len(bad) == 0, f"Found hardcoded self.model = 'qwen...': {bad}"


if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))
